sudo: true

language: rust

cache: cargo

dist: xenial

rust:
  - stable

os:
  - linux

matrix:
  include:
    - os: linux
    - os: linux
      rust: 1.36.0
    - os: linux
      env: RUSTFMT=yes
    - os: linux
      env: CLIPPY=yes

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_cache:
- find ./target/debug -maxdepth 1 -type f -delete
- rm -rf ./target/debug/deps/tinytemplate*
- rm -rf ./target/debug/.fingerprint/tinytemplate*
- rm -f  ./target/.rustc_info.json
- rm -rf ~/.cargo/registry/index/

branches:
  only: master

notifications:
  email:
    on_success: never
