sudo: true

language: rust

cache: cargo

dist: xenial

rust:
  - stable

os:
  - linux

matrix:
  include:
    - os: linux
    - os: linux
      rust: 1.29.0
    - os: linux
      rust: 1.30.0
    - os: linux
      rust: 1.31.0
    - os: linux
      rust: 1.32.0
    - os: linux
      rust: 1.33.0
    - os: linux
      rust: 1.34.0
    - os: linux
      rust: 1.35.0
    - os: linux
      rust: 1.36.0
    - os: linux
      rust: 1.37.0
    - os: linux
      rust: 1.38.0
    - os: linux
      rust: 1.39.0
    - os: linux
      rust: 1.40.0
    - os: linux
      env: RUSTFMT=yes
    - os: linux
      env: CLIPPY=yes

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

branches:
  only: master

notifications:
  email:
    on_success: never
