[package]
name = "tinytemplate"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]
edition = "2015"

[dependencies]
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
serde_derive = "1.0"
criterion = "0.2"

[[bench]]
name = "benchmarks"
harness = false