on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.36.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - run: cargo test

      - if: ${{ matrix.rust == "stable" }}
        run: cargo fmt --all -- --check
        
      - if: ${{ matrix.rust == "stable" }}
        run: cargo clippy --all -- -D warnings
